### ISSUE TITLE
cdn

### ISSUE THREAD

**Issue by timreichen** [DefinitelyMaybe/threejs_4_deno#1]
Not a real issue, but what is the point of using this module instead of a cdn like skypack.dev, esm.sh, jspm.dev or unpkg.com like described on their [website](https://threejs.org/docs/#manual/en/introduction/Installation)?

**Comment by DefinitelyMaybe** [comment]
you're more than welcome to do either

**Comment by timreichen** [comment]
Sorry, my question was not precisely formed: What is the advantage of using this module?

**Comment by DefinitelyMaybe** [comment]
oh. small things. looking through the `main.ts` script will tell you all the differences. it's mostly around urls and triple slash references because I wanted them.

**Comment by DefinitelyMaybe** [comment]
I'm going to close this issue and thank @timreichen.

I didn't know about [skypack.dev/three](https://www.skypack.dev/view/three).

Here's a link to [skypack.dev talking about deno](https://docs.skypack.dev/skypack-cdn/code/deno)
